### ISSUE TITLE
Z-index

### ISSUE THREAD

**Issue by bsherms** [bsherms/interactive-polaroids#1]
@thomasjbradley

Markbot says "The pteranodon doesn't change z-index when hovered." and I am confused by what this means. The Pteranodon is my second child in the css.

https://github.com/bsherms/interactive-polaroids/blob/gh-pages/css/main.css#L39-L56

**Comment by thomasjbradley** [comment]
Have you tried making the z-index much higher, like `1000`?

**Comment by bsherms** [comment]
Interesting... thank you! Does the z-index have to be extremely different for Markbot to notice or is that what would be necessary for the code to respond properly?

**Comment by thomasjbradley** [comment]
The `z-index: 5` should work, no problem, and I’m a little confused as to why it wasn’t being picked up by Markbot.

**Comment by thomasjbradley** [comment]
For the stegosaurus problem: try using `:nth-child(3)` instead of `:last-child`. Last child is completely correct, but Markbot injects stuff into the bottom of your document, meaning that polaroid is no longer the last child.
